<?php
$_instagram = $this->getInstagramdefault();
//var_dump($instagram);die;
$default_items = (int)$this->getConfig("default_items");
$default_items = !empty($default_items)?$default_items:5;

$mobile_items = (int)$this->getConfig("mobile_items");
$mobile_items = !empty($mobile_items)?$mobile_items:1;

$tablet_small_items = (int)$this->getConfig("tablet_small_items");
$tablet_small_items = !empty($tablet_small_items)?$tablet_small_items:2;

$tablet_items = (int)$this->getConfig("tablet_items");
$tablet_items = !empty($mobile_items)?$tablet_items:4;

$itemsperpage = (int)$this->getConfig("limit");
$itemsperpage = !empty($itemsperpage)?$itemsperpage:8;
$i  = 0;
$id = rand(1,10)+rand();
?>


<div id="ves-instagram" class="block ves-brandcarousel">
	<?php if( count($_instagram) ) { ?>
	<div class="block-content">
		<div class="item-box-title hidden-md hidden-lg">
				<?php if($this->getConfig('title')){?>
				<div class="block-title">
					<h2><?php echo $this->getConfig('title')?></h2>
				</div>
				<?php }?>
			</div>
		<?php
		$number = 0;
		foreach ($_instagram->data as $media) { $i++?>
		<?php if($i == 1 || ($i-1) % $itemsperpage == 0) { ?>
		<div class="row">
			<?php } ?>
			<?php
			// image
			$link = $media->link;
			$image = $media->images->low_resolution->url;
			$image_large = $media->images->standard_resolution->url;
			$width_large = $media->images->standard_resolution->width;
			$height_large = $media->images->standard_resolution->height;
			$avatar = $media->user->profile_picture;
			$username = $media->user->username;
			$comment = (!empty($media->caption->text)) ? $media->caption->text : '';
			?>
			<?php if ($number == $default_items) { ?>
			<div class="item-box-title hidden-xs hidden-sm" >
				<?php if($this->getConfig('title')){?>
				<div class="block-title">
					<h2><?php echo $this->getConfig('title')?></h2>
					<span><?php echo $this->__('Follow us')?></span>
				</div>
				<?php }?>
			</div>
			<?php } ?>
			<div class="item-instagram">
				<a class="colorbox-instagram_<?php echo $number; ?>" href="#instagram-detail_<?php echo $number; ?>">
					<img style="width: <?php echo $this->getWidthinconfig() ?>px; height: <?php echo $this->getHeightinconfig() ?>px;" alt="" src="<?php echo $image ?>"/>
				</a>
				<div id="instagram-detail_<?php echo $number; ?>" >
					<img width="<?php echo $width_large ?>" height="<?php echo $height_large ?>" class="media" alt="" src="<?php echo $image_large ?>"/>
					<div class="instagram-content">
						<div class="instagram-avatar" style="background-image: url(<?php echo $avatar ?>)"></div>
						<p><a target="_blank" href="<?php echo $link ?>"><?php echo $username ?></a></p>
						<div class="instagram-comment"><?php echo $comment ?></div>
					</div>
				</div>
				<script type="text/javascript"><!--
					jQuery(document).ready(function() {
						jQuery('.colorbox-instagram_<?php echo $number; ?>').colorbox({inline:true, width:"50%"});
						jQuery('#instagram-detail_<?php echo $number; ?>').hide();
						jQuery('.colorbox-instagram_<?php echo $number; ?>').click(function(){
							jQuery('#instagram-detail_<?php echo $number; ?>').show();
						});
						jQuery(document).bind('cbox_closed', function(){
							jQuery('#instagram-detail_<?php echo $number; ?>').hide();
						});
					});
				//-->
			</script> 
			<?php $number ++; ?>
		</div>
		<?php if( $i%$itemsperpage==0 || $i==$itemsperpage) { ?>
	</div>
	<?php } ?>
	<?php }?>
</div>
<?php } //end if ?>
</div>
<script type="text/javascript">
jQuery( window ).resize(function() {
	ResizeWidth();
});
jQuery(window).load(function() {
	ResizeWidth();
});
function ResizeWidth(){
			var totalwidth = jQuery("#ves-instagram").outerWidth(true);
			var totalwidthBody = jQuery("body").outerWidth(true);
			var cols = 5;
			if (totalwidthBody >= 980 && totalwidthBody <= 1199) {
				 cols = <?php echo $default_items ?>;
			}else if (totalwidthBody <= 480) {
				 cols = <?php echo $mobile_items ?>;
			}else if (totalwidthBody >= 480 &&  totalwidthBody <= 641) {
				 cols = <?php echo $tablet_small_items ?>;
			}else if (totalwidthBody >= 641 &&  totalwidthBody <= 768) {
				 cols = <?php echo $tablet_items ?>;
			}
			//console.log(cols+'-'+totalwidth+'-'+totalwidthBody);
			var first_total = totalwidth/cols;
			var width_default = Math.round(first_total-2).toString();
			var width2 = Math.round((first_total-2) * 2).toString();

			jQuery( ".item-instagram" ).width(width_default);
			jQuery( ".item-box-title" ).width(width2);
			jQuery( ".item-box-title" ).height(<?php echo $height ?>);
}
</script>
