<?php 
/*Owl Carousel Setting*/
	$auto_play_mode = $this->getCarouselConfig("auto_play");
	$interval = (int)$this->getCarouselConfig("interval");
	$lazy_load_image = $this->getCarouselConfig("lazy_load_image", 0);
	$loop = (int)$this->getCarouselConfig("loop", 1);
	$slide_by = (int)$this->getCarouselConfig("slide_by", 1);
	$margin_item = $this->getCarouselConfig("margin_item", 0);
	$show_nav = (int)$this->getCarouselConfig("show_navigator", 1);
	$rtl = (int)$this->getCarouselConfig("rtl", 0);
	$mouse_drag = (int)$this->getCarouselConfig("mouse_drag", 1);
	$touch_drag = (int)$this->getCarouselConfig("touch_drag", 1);
	$mobile_items = (int)$this->getCarouselConfig("mobile_items", 1);
	$tablet_items = (int)$this->getCarouselConfig("tablet_items", 2);
	$tablet_small_items = (int)$this->getCarouselConfig("tablet_small_items", 2);
	$portrait_items = (int)$this->getCarouselConfig("portrait_items", 3);
	$large_items = (int)$this->getCarouselConfig("large_items", 5);
	$custom_items = $this->getCarouselConfig("custom_items", "");

	$carousel_responsive = (int)$this->getCarouselConfig("carousel_responsive", 1);
	$cols = (int)$this->getCarouselConfig("default_items", 4);
	$cols = !empty($cols)?(int)$cols:4;
	$itemsperpage = (int)$this->getConfig("max_items", 1);
	$auto_play = $auto_play_mode?"true":"false";
	
	$default_items = $cols;

$moduleId = "vesgallery".rand().time();
?>
<?php 
	$style = "";
	if( $this->getConfig("moduleHeight") !="auto" ){
		$style .=";height:".(int) $this->getConfig("moduleHeight")."px";
	}
	if( $this->getConfig("moduleWidth") !="auto" ){
		$style .=";width:".(int) $this->getConfig("moduleWidth")."px";
	}
?>
<div class="ves-gallery block" style="position:relative;<?php echo $style;?>">
	<?php if($this->getConfig('title')){?>
	<div class="block-title">
		<h2><?php echo $this->getConfig('title')?></h2>
	</div>
	<?php }?>
	<?php if( count($this->getImages()) ) { ?>

		<div class="block-content">
		<div class="box-products carousel slide">
			<div id="owlgallery<?php echo $moduleId;?>" class="owl-carousel">
				<?php
					$pages = array_chunk( $this->getImages(), $itemsperpage);
				?>
				<?php $number = 1; ?>
				<?php foreach ($pages as  $k => $tmpgallery ):  ?>
						<div class="item <?php if($k==0) {?>first<?php } elseif($k == (count($pages) -1 )) {?>last<?php } ?> products-grid no-margin">
						<?php foreach( $tmpgallery as $i => $image ) {  $i=$i+1;?>
						<?php if( $cols == 1 || $i%$cols == 1 ) { ?>
						<div class="row">
						<?php } ?>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 item-col">
							<div class="w-gallery">
								<a class="group-file<?php echo $rad?> group-file" href="<?php echo $image['imageURL'];?>" title="<?php echo $image['title'];?> - <?php echo $image['description']; ?>">
									<img src="<?php echo $image['thumbnailURL'];?>" alt="<?php echo $image['title'];?>"/>
									<i class="fa fa-search-plus"></i>
								</a>
								<div class="desc-gallery">
							        <div class="gellary-title"><?php echo $image['title'];?></div>
							        <div class="gellary-description"><?php echo Mage::helper("ves_tempcp")->subString($image['description'], 100, "");?></div>
						        </div> 
								<div class="links"> 
									<a href="<?php echo $image['links']; ?> ">Links</a>
								</div>
							</div>
						</div>
						<?php if( $cols==1 || $i%$cols == 0 || $i==count($tmpgallery) ) { ?>
						</div>
					<?php } ?>
					<?php $number ++; } //endforeach 2?>
						</div>
				<?php endforeach; ?>
			</div>
	</div>
</div>
<?php } //end if ?>
</div>

<script type="text/javascript">
jQuery(window).load(function() {
	var owl = jQuery('#owlgallery<?php echo $moduleId;?>');
        owl.owlCarousel({
            autoPlay: <?php echo $auto_play_mode?'true':'false';?>,
            slideSpeed: <?php echo $interval?(int)$interval:'500';?>,
            autoplayHoverPause: true,
            <?php if($lazy_load_image) { ?>
            lazyLoad:true,
            <?php } ?>
            navigationText: ["<span class='fa fa-long-arrow-left'></span>","<span class='fa fa-long-arrow-right'></span>"],
            slideBy: <?php echo (isset($slide_by) && $slide_by)?(int)$slide_by:1; ?>,
            loop: <?php echo $loop == 1?'true':'false'; ?>,
            margin: <?php echo $margin_item?(int)$margin_item:'0'; ?>,
            navigation: <?php echo $show_nav == 1?'true':'false'; ?>,
            rtl: <?php echo $rtl == 1?'true':'false'; ?>,
            mouseDrag: <?php echo $mouse_drag == 1?'true':'false'; ?>,
            touchDrag: <?php echo $touch_drag == 1?'true':'false'; ?>,
            autoWidth: false,
            responsive: true,
            items: <?php echo $default_items?(int)$default_items:4; ?>,
            itemsDesktop : [1199,<?php echo $default_items?(int)$default_items:4; ?>], //4 items between 1199px and 980px
            itemsDesktopSmall : [979,<?php echo $portrait_items?(int)$portrait_items:3; ?>], //3 items betweem 979px and 769px
            itemsTablet: [768, <?php echo $tablet_items?(int)$tablet_items:2; ?>], //2 items between 768px and 641px
            itemsTabletSmall : [640, <?php echo $tablet_small_items?(int)$tablet_small_items:2; ?>], //2 items between 641px and 480px
            itemsMobile : [479, <?php echo $mobile_items?(int)$mobile_items:1; ?>], // itemsMobile disabled - inherit from itemsTablet option
            itemsCustom: <?php echo isset($custom_items)?'['.$custom_items.']':'false';?> // custom numbers item view on screen
        });
});
</script>
<script type="text/javascript">
jQuery(document).ready(function( $ ){
	$(".group-file<?php echo $rad?>").colorbox({rel:'group1'});
});
</script>