<?php
	$modid = rand().time();
	$enable_collapse = $this->getConfig("enable_collapse", 0);
?>
<div class="block block-list block-facebook-widget">
	<?php if(trim($title)!=''): ?>
		<div class="block-title">
			<?php if($enable_collapse): ?><span class="opener hidden-lg hidden-md" data-toggle="collapse" data-target="#widget-facebook<?php echo $modid; ?>"><i class="fa fa-angle-down"></i></span><?php endif; ?>
			<strong><span><?php echo $title; ?></span></strong>
		</div>
	<?php endif; ?>
	<div id="widget-facebook<?php echo $modid; ?>" class="widget-inner block-content <?php if($enable_collapse): ?> widget-enanle-collapse collapse in <?php endif; ?>">
		<iframe src="//www.facebook.com/plugins/likebox.php?href=<?php echo $url; ?>&amp;height=<?php echo $height; ?>&amp;colorscheme=<?php echo $theme; ?>&amp;show_faces=<?php echo $showfriends; ?>&amp;header=<?php echo $header; ?>&amp;stream=<?php echo $posts; ?>&amp;show_border=<?php echo $border; ?>&amp;appId=<?php echo $app_id; ?>" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:<?php echo $height; ?>;width:<?php echo $width;?>; <?php echo $css ?>" allowTransparency="true"></iframe>
	</div>
</div>