<?php

if ($PS_SC_TWITTER || $PS_SC_FACEBOOK || $PS_SC_GOOGLE || $PS_SC_PINTEREST): ?>
	<p class="ptssocialsharing_product list-inline no-print">
		{if $PS_SC_TWITTER}
			<button type="button" class="btn btn-default btn-twitter" onclick="ptssocialsharing_twitter_click('{$pagename|addslashes} {$pagelink|addslashes}');">
				<i class="icon-twitter"></i> <span>Tweet</span>
				<!-- <img src="{$link->getMediaLink("`$module_dir`img/twitter.gif")}" alt="Tweet" /> -->
			</button>
		{/if}
		{if $PS_SC_FACEBOOK}
			<button type="button" class="btn btn-default btn-facebook" onclick="ptssocialsharing_facebook_click();">
				<i class="icon-facebook"></i><span> facebook</span>
				<!-- <img src="{$link->getMediaLink("`$module_dir`img/facebook.gif")}" alt="Facebook Like" /> -->
			</button>
		{/if}
		{if $PS_SC_GOOGLE}
			<button type="button" class="btn btn-default btn-google-plus" onclick="ptssocialsharing_google_click();">
				<i class="icon-google-plus"></i> <span>Google+</span>
				<!-- <img src="{$link->getMediaLink("`$module_dir`img/google.gif")}" alt="Google Plus" /> -->
			</button>
		{/if}
		{if $PS_SC_PINTEREST}
			<button type="button" class="btn btn-default btn-pinterest" onclick="ptssocialsharing_pinterest_click();">
				<i class="icon-pinterest"></i> <span>Pinterest</span>
				<!-- <img src="{$link->getMediaLink("`$module_dir`img/pinterest.gif")}" alt="Pinterest" /> -->
			</button>
		{/if}
	</p>
<?php endif; ?>